[package]
name = "z3s-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
thiserror.workspace = true
serde.workspace = true
blake3.workspace = true
md-5.workspace = true
sha2.workspace = true
crc32fast.workspace = true
hex.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
quick-xml.workspace = true
