[package]
name = "z3s-metadata"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
z3s-common.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true
uuid.workspace = true
crc32fast.workspace = true
bytes.workspace = true
