[package]
name = "z3s-gateway"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
z3s-common.workspace = true
z3s-auth.workspace = true
z3s-erasure.workspace = true
z3s-storage.workspace = true
z3s-metadata.workspace = true
z3s-cluster.workspace = true
z3s-kms.workspace = true
tokio.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
tower.workspace = true
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
hex.workspace = true

[dev-dependencies]
tempfile.workspace = true
